export const getAllPacientes = () => {
  return [
    {
      id: "0",
      nome: "João Batista Moreira",
      idade: 45,
      cpf: "123.456.789-00",
      rg: "12.345.678-9",
      endereco: "Rua das Flores, 123 - Centro - São Paulo/SP",
      telefone: "(11) 99999-9999",
      email: "joao.moreira@email.com",
      convenio: "UNIMED",
      numeroCartao: "123456789012345",
      procedimento: "Herniorrafia Inguinal",
      cirurgiao: "Dr. Ricardo Salles",
      anestesista: "Dr. Carlos Silva",
      instrumentadora: "Enf. Maria Santos",
      sala: 1,
      status: "SRPA",
      lateralidade: "DIREITO",
      alergias: "Dipirona, Penicilina",
      observacoes: "Paciente hipertenso, em uso de Losartana 50mg",
      contatoEmergencia: "Maria Moreira (Esposa)",
      telefoneEmergencia: "(11) 98888-8888",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "1",
      nome: "Fabiana Lopes Martins",
      idade: 54,
      cpf: "234.567.890-11",
      rg: "23.456.789-0",
      endereco: "Av. Paulista, 456 - Bela Vista - São Paulo/SP",
      telefone: "(11) 98888-7777",
      email: "fabiana.martins@email.com",
      convenio: "BRADESCO",
      numeroCartao: "234567890123456",
      procedimento: "Colecistectomia Videolaparosc.",
      cirurgiao: "Dra. Ricardo Salles",
      anestesista: "Dr. Paulo Mendes",
      instrumentadora: "Enf. Carla Lima",
      sala: 1,
      status: "CHAMADO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Paciente diabética, glicemia controlada",
      contatoEmergencia: "Roberto Martins (Marido)",
      telefoneEmergencia: "(11) 97777-6666",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "2",
      nome: "Jonas Pedroso Carvalho",
      idade: 72,
      cpf: "345.678.901-22",
      rg: "34.567.890-1",
      endereco: "Rua Augusta, 789 - Consolação - São Paulo/SP",
      telefone: "(11) 97777-6666",
      email: "jonas.carvalho@email.com",
      convenio: "GOLDEN",
      numeroCartao: "345678901234567",
      procedimento: "Histerectomia Vaginal",
      cirurgiao: "Dr. Fábio Moura",
      anestesista: "Dr. Ricardo Alves",
      instrumentadora: "Enf. Sandra Costa",
      sala: 1,
      status: "RECEPÇÃO",
      lateralidade: "N/A",
      alergias: "Alergia a contraste iodado",
      observacoes: "Paciente com histórico de IAM, em uso de AAS",
      contatoEmergencia: "Helena Carvalho (Filha)",
      telefoneEmergencia: "(11) 96666-5555",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "3",
      nome: "Raquel Lima Andrade",
      idade: 47,
      cpf: "456.789.012-33",
      rg: "45.678.901-2",
      endereco: "Rua Oscar Freire, 321 - Jardins - São Paulo/SP",
      telefone: "(11) 96666-5555",
      email: "raquel.andrade@email.com",
      convenio: "PARTICULAR",
      numeroCartao: "N/A",
      procedimento: "Varizes Membros Inferiores",
      cirurgiao: "Dra. Letícia Noronha",
      anestesista: "Dr. Fernando Costa",
      instrumentadora: "Enf. Patricia Souza",
      sala: 1,
      status: "EXTERNO",
      lateralidade: "BILATERAL",
      alergias: "Látex",
      observacoes: "Paciente com varizes grau III bilateral",
      contatoEmergencia: "Carlos Andrade (Marido)",
      telefoneEmergencia: "(11) 95555-4444",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "4",
      nome: "Luís Carlos Damasceno",
      idade: 68,
      cpf: "567.890.123-44",
      rg: "56.789.012-3",
      endereco: "Rua Haddock Lobo, 654 - Cerqueira César - São Paulo/SP",
      telefone: "(11) 95555-4444",
      email: "luis.damasceno@email.com",
      convenio: "UNIMED",
      numeroCartao: "567890123456789",
      procedimento: "Prostatectomia Radical Robótica",
      cirurgiao: "Dr. Daniel Tavares",
      anestesista: "Dr. Marcos Ribeiro",
      instrumentadora: "Enf. Juliana Alves",
      sala: 2,
      status: "EM ANDAMENTO",
      lateralidade: "N/A",
      alergias: "Morfina",
      observacoes: "PSA elevado, biópsia positiva para adenocarcinoma",
      contatoEmergencia: "Silvia Damasceno (Esposa)",
      telefoneEmergencia: "(11) 94444-3333",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "5",
      nome: "Márcia Soares Ribeiro",
      idade: 59,
      cpf: "678.901.234-55",
      rg: "67.890.123-4",
      endereco: "Av. Brigadeiro Faria Lima, 987 - Itaim Bibi - São Paulo/SP",
      telefone: "(11) 94444-3333",
      email: "marcia.ribeiro@email.com",
      convenio: "SULAMÉRICA",
      numeroCartao: "678901234567890",
      procedimento: "Facoemulsificação",
      cirurgiao: "Dra. Carolina Paes",
      anestesista: "Dr. Luiz Henrique",
      instrumentadora: "Enf. Beatriz Santos",
      sala: 2,
      status: "APO",
      lateralidade: "DIREITO",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Catarata senil, AV 20/200 OD",
      contatoEmergencia: "José Ribeiro (Marido)",
      telefoneEmergencia: "(11) 93333-2222",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "6",
      nome: "Maria Pinto Fagundes",
      idade: 41,
      cpf: "789.012.345-66",
      rg: "78.901.234-5",
      endereco: "Rua Consolação, 456 - Consolação - São Paulo/SP",
      telefone: "(11) 93333-2222",
      email: "maria.fagundes@email.com",
      convenio: "BRADESCO",
      numeroCartao: "789012345678901",
      procedimento: "Laqueadura Tubária",
      cirurgiao: "Dr. Gustavo Vidal",
      anestesista: "Dra. Fernanda Lima",
      instrumentadora: "Enf. Roberta Costa",
      sala: 2,
      status: "QUARTO",
      lateralidade: "N/A",
      alergias: "Ibuprofeno",
      observacoes: "G3P2A1, deseja contracepção definitiva",
      contatoEmergencia: "Carlos Fagundes (Marido)",
      telefoneEmergencia: "(11) 92222-1111",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "7",
      nome: "Eliane de Castro Ferreira",
      idade: 66,
      cpf: "890.123.456-77",
      rg: "89.012.345-6",
      endereco: "Rua da Liberdade, 789 - Liberdade - São Paulo/SP",
      telefone: "(11) 92222-1111",
      email: "eliane.ferreira@email.com",
      convenio: "FUSEX",
      numeroCartao: "890123456789012",
      procedimento: "Histeroscopia Diagnóstica",
      cirurgiao: "Dr. Gustavo Vidal",
      anestesista: "Dr. Roberto Silva",
      instrumentadora: "Enf. Claudia Mendes",
      sala: 2,
      status: "EXTERNO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Sangramento uterino anormal pós-menopausa",
      contatoEmergencia: "Paulo Ferreira (Filho)",
      telefoneEmergencia: "(11) 91111-0000",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "8",
      nome: "Jorge Almeida Rocha",
      idade: 50,
      cpf: "901.234.567-88",
      rg: "90.123.456-7",
      endereco: "Av. Ipiranga, 321 - República - São Paulo/SP",
      telefone: "(11) 91111-0000",
      email: "jorge.rocha@email.com",
      convenio: "UNIMED",
      numeroCartao: "901234567890123",
      procedimento: "Nefrolitotripsia Flexível",
      cirurgiao: "Dr. Leonardo S. Dias",
      anestesista: "Dr. Marcelo Santos",
      instrumentadora: "Enf. Vanessa Lima",
      sala: 3,
      status: "ALTA",
      lateralidade: "DIREITO",
      alergias: "Contraste iodado",
      observacoes: "Cálculo renal 15mm em pelve renal direita",
      contatoEmergencia: "Sandra Rocha (Esposa)",
      telefoneEmergencia: "(11) 90000-9999",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "9",
      nome: "Simone Meirelles Dutra",
      idade: 37,
      cpf: "012.345.678-99",
      rg: "01.234.567-8",
      endereco: "Rua Bela Cintra, 654 - Consolação - São Paulo/SP",
      telefone: "(11) 90000-9999",
      email: "simone.dutra@email.com",
      convenio: "PARTICULAR",
      numeroCartao: "N/A",
      procedimento: "Colecistectomia Videolaparosc.",
      cirurgiao: "Dr. Eduardo Ramos",
      anestesista: "Dra. Patricia Alves",
      instrumentadora: "Enf. Monica Silva",
      sala: 3,
      status: "EM ANDAMENTO",
      lateralidade: "N/A",
      alergias: "Penicilina",
      observacoes: "Colelitíase sintomática, múltiplos cálculos",
      contatoEmergencia: "Ricardo Dutra (Marido)",
      telefoneEmergencia: "(11) 89999-8888",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "10",
      nome: "Nelson Garcia Teixeira",
      idade: 41,
      cpf: "123.456.789-10",
      rg: "12.345.678-0",
      endereco: "Av. Rebouças, 987 - Pinheiros - São Paulo/SP",
      telefone: "(11) 89999-8888",
      email: "nelson.teixeira@email.com",
      convenio: "CASSI",
      numeroCartao: "123456789012340",
      procedimento: "By-pass gástrico",
      cirurgiao: "Dr. Eduardo Ramos",
      anestesista: "Dr. Felipe Costa",
      instrumentadora: "Enf. Adriana Santos",
      sala: 3,
      status: "CHAMADO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "IMC 42, diabetes tipo 2, hipertensão",
      contatoEmergencia: "Cristina Teixeira (Esposa)",
      telefoneEmergencia: "(11) 88888-7777",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "11",
      nome: "Roberta Soares Silveira",
      idade: 34,
      cpf: "234.567.890-21",
      rg: "23.456.789-1",
      endereco: "Rua Pamplona, 456 - Jardim Paulista - São Paulo/SP",
      telefone: "(11) 88888-7777",
      email: "roberta.silveira@email.com",
      convenio: "BRADESCO",
      numeroCartao: "234567890123451",
      procedimento: "Artroscopia de Joelho",
      cirurgiao: "Dra. Fernanda C. Luz",
      anestesista: "Dr. Rodrigo Lima",
      instrumentadora: "Enf. Camila Costa",
      sala: 3,
      status: "SUSPENSA",
      lateralidade: "ESQUERDO",
      alergias: "Dipirona",
      observacoes: "Lesão de menisco medial, atleta recreativa",
      contatoEmergencia: "Marcos Silveira (Marido)",
      telefoneEmergencia: "(11) 87777-6666",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "12",
      nome: "Otávio Marques Gonçalves",
      idade: 64,
      cpf: "345.678.901-32",
      rg: "34.567.890-2",
      endereco: "Rua Estados Unidos, 789 - Jardim América - São Paulo/SP",
      telefone: "(11) 87777-6666",
      email: "otavio.goncalves@email.com",
      convenio: "GOLDEN",
      numeroCartao: "345678901234562",
      procedimento: "Osteossíntese de Úmero",
      cirurgiao: "Dr. Carlos H. Bittencourt",
      anestesista: "Dr. Anderson Silva",
      instrumentadora: "Enf. Priscila Lima",
      sala: 4,
      status: "SRPA",
      lateralidade: "DIREITO",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Fratura de úmero proximal pós-queda",
      contatoEmergencia: "Vera Gonçalves (Esposa)",
      telefoneEmergencia: "(11) 86666-5555",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "13",
      nome: "Beatriz Antunes Ferreira",
      idade: 25,
      cpf: "456.789.012-43",
      rg: "45.678.901-3",
      endereco: "Av. Paulista, 1234 - Bela Vista - São Paulo/SP",
      telefone: "(11) 86666-5555",
      email: "beatriz.ferreira@email.com",
      convenio: "UNIMED",
      numeroCartao: "456789012345673",
      procedimento: "Artroplastia de quadril",
      cirurgiao: "Dr. Carlos H. Bittencourt",
      anestesista: "Dra. Juliana Mendes",
      instrumentadora: "Enf. Fernanda Silva",
      sala: 4,
      status: "EM ANDAMENTO",
      lateralidade: "DIREITO",
      alergias: "Látex, Iodo",
      observacoes: "Displasia congênita do quadril, jovem atleta",
      contatoEmergencia: "Maria Antunes (Mãe)",
      telefoneEmergencia: "(11) 85555-4444",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "14",
      nome: "Pedro Vitor Saldanha",
      idade: 39,
      cpf: "567.890.123-54",
      rg: "56.789.012-4",
      endereco: "Rua Augusta, 2468 - Consolação - São Paulo/SP",
      telefone: "(11) 85555-4444",
      email: "pedro.saldanha@email.com",
      convenio: "AMIL",
      numeroCartao: "567890123456784",
      procedimento: "Cirurgia de Hemorroida",
      cirurgiao: "Dr. Álvaro Gonçalves",
      anestesista: "Dr. Thiago Santos",
      instrumentadora: "Enf. Larissa Costa",
      sala: 4,
      status: "APO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Hemorroidas grau III, sintomas há 2 anos",
      contatoEmergencia: "Amanda Saldanha (Esposa)",
      telefoneEmergencia: "(11) 84444-3333",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "15",
      nome: "Elza Maria Coimbra",
      idade: 73,
      cpf: "678.901.234-65",
      rg: "67.890.123-5",
      endereco: "Rua Bela Cintra, 1357 - Consolação - São Paulo/SP",
      telefone: "(11) 84444-3333",
      email: "elza.coimbra@email.com",
      convenio: "UNIMED",
      numeroCartao: "678901234567895",
      procedimento: "Reconstrução de Parede Abdominal",
      cirurgiao: "Dra. Patrícia Fontes",
      anestesista: "Dr. Gustavo Lima",
      instrumentadora: "Enf. Renata Santos",
      sala: 4,
      status: "CTI",
      lateralidade: "N/A",
      alergias: "Penicilina, Sulfa",
      observacoes: "Hérnia incisional complexa, múltiplas comorbidades",
      contatoEmergencia: "Carlos Coimbra (Filho)",
      telefoneEmergencia: "(11) 83333-2222",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "16",
      nome: "Bruno César Machado",
      idade: 22,
      cpf: "789.012.345-76",
      rg: "78.901.234-6",
      endereco: "Av. Brigadeiro Luis Antonio, 987 - Bela Vista - São Paulo/SP",
      telefone: "(11) 83333-2222",
      email: "bruno.machado@email.com",
      convenio: "SULAMÉRICA",
      numeroCartao: "789012345678906",
      procedimento: "Orquiectomia",
      cirurgiao: "Dr. Henrique de Sá",
      anestesista: "Dr. Rafael Costa",
      instrumentadora: "Enf. Tatiana Lima",
      sala: 5,
      status: "EM ANDAMENTO",
      lateralidade: "ESQUERDO",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Tumor testicular, marcadores elevados",
      contatoEmergencia: "Lucia Machado (Mãe)",
      telefoneEmergencia: "(11) 82222-1111",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "17",
      nome: "Luciana Esteves Paiva",
      idade: 36,
      cpf: "890.123.456-87",
      rg: "89.012.345-7",
      endereco: "Rua Oscar Freire, 654 - Jardins - São Paulo/SP",
      telefone: "(11) 82222-1111",
      email: "luciana.paiva@email.com",
      convenio: "BRADESCO",
      numeroCartao: "890123456789017",
      procedimento: "Histerectomia Videolaparoscópica",
      cirurgiao: "Dra. Lúcia Andrade",
      anestesista: "Dr. Marcelo Ribeiro",
      instrumentadora: "Enf. Silvia Santos",
      sala: 5,
      status: "CHAMADO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Miomatose uterina, sangramento abundante",
      contatoEmergencia: "Fernando Paiva (Marido)",
      telefoneEmergencia: "(11) 81111-0000",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "18",
      nome: "Edson Alves Guimarães",
      idade: 53,
      cpf: "901.234.567-98",
      rg: "90.123.456-8",
      endereco: "Av. Faria Lima, 1234 - Itaim Bibi - São Paulo/SP",
      telefone: "(11) 81111-0000",
      email: "edson.guimaraes@email.com",
      convenio: "UNIMED",
      numeroCartao: "901234567890128",
      procedimento: "Vasectomia",
      cirurgiao: "Dr. André Peixoto",
      anestesista: "Dr. Paulo Santos",
      instrumentadora: "Enf. Cristina Lima",
      sala: 5,
      status: "APO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Prole constituída, deseja contracepção definitiva",
      contatoEmergencia: "Patricia Guimarães (Esposa)",
      telefoneEmergencia: "(11) 80000-9999",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
    {
      id: "19",
      nome: "Carlos Maia Marcondes",
      idade: 61,
      cpf: "012.345.678-09",
      rg: "01.234.567-9",
      endereco: "Rua Haddock Lobo, 2468 - Jardim Paulista - São Paulo/SP",
      telefone: "(11) 80000-9999",
      email: "carlos.marcondes@email.com",
      convenio: "AMIL",
      numeroCartao: "012345678901239",
      procedimento: "Vasectomia",
      cirurgiao: "Dr. André Peixoto",
      anestesista: "Dr. Sergio Lima",
      instrumentadora: "Enf. Daniela Costa",
      sala: 5,
      status: "RECEPÇÃO",
      lateralidade: "N/A",
      alergias: "Dipirona",
      observacoes: "Prole constituída, 3 filhos adultos",
      contatoEmergencia: "Marisa Marcondes (Esposa)",
      telefoneEmergencia: "(11) 79999-8888",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [],
    },
  ]
}