export const getAllPacientes = () => {
  return [
    {
      id: "0",
      nome: "João Batista Moreira",
      idade: 45,
      cpf: "123.456.789-00",
      rg: "12.345.678-9",
      endereco: "Rua das Flores, 123 - Centro - São Paulo/SP",
      telefone: "(11) 99999-9999",
      email: "joao.moreira@email.com",
      convenio: "UNIMED",
      numeroCartao: "123456789012345",
      procedimento: "Herniorrafia Inguinal",
      cirurgiao: "Dr. Ricardo Salles",
      anestesista: "Dr. Carlos Silva",
      instrumentadora: "Enf. Maria Santos",
      sala: 1,
      status: "ALTA", // Changed to ALTA for completed surgery
      lateralidade: "DIREITO",
      alergias: "Dipirona, Penicilina",
      observacoes: "Paciente hipertenso, em uso de Losartana 50mg",
      contatoEmergencia: "Maria Moreira (Esposa)",
      telefoneEmergencia: "(11) 98888-8888",
      horarios: [
        { tipo: "ENTRADA EM SALA", horario: "07:15", usuario: "Enf. Ana Silva", timestamp: "2025-01-04T07:15:00Z" },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "07:30",
          usuario: "Dr. Carlos Silva",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "07:45",
          usuario: "Dr. Ricardo Salles",
          timestamp: "2025-01-04T07:45:00Z",
        },
        { tipo: "FIM DA CIRURGIA", horario: "08:30", usuario: "Dr. Ricardo Salles", timestamp: "2025-01-04T08:30:00Z" },
        { tipo: "FIM DA ANESTESIA", horario: "08:45", usuario: "Dr. Carlos Silva", timestamp: "2025-01-04T08:45:00Z" },
        { tipo: "SAÍDA DE SALA", horario: "09:00", usuario: "Enf. Ana Silva", timestamp: "2025-01-04T09:00:00Z" },
      ],
      historico: [
        {
          data: "15/03/2023",
          procedimento: "Apendicectomia",
          cirurgiao: "Dr. João Santos",
          hospital: "Hospital São Lucas",
          observacoes: "Procedimento sem intercorrências",
        },
      ],
      contatosFamiliares: [
        { nome: "Maria Moreira", parentesco: "Esposa", telefone: "(11) 98888-8888", receberNotificacoes: true },
        { nome: "Pedro Moreira", parentesco: "Filho", telefone: "(11) 97777-7777", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "06:30",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T06:30:00Z",
        },
        {
          tempo: "07:00",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Ana Silva",
          timestamp: "2025-01-04T07:00:00Z",
        },
        {
          tempo: "07:15",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Ana Silva",
          timestamp: "2025-01-04T07:15:00Z",
        },
        {
          tempo: "07:30",
          evento: "Início da anestesia",
          usuario: "Dr. Carlos Silva",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tempo: "07:45",
          evento: "Início da cirurgia",
          usuario: "Dr. Ricardo Salles",
          timestamp: "2025-01-04T07:45:00Z",
        },
        { tempo: "08:30", evento: "Fim da cirurgia", usuario: "Dr. Ricardo Salles", timestamp: "2025-01-04T08:30:00Z" },
        { tempo: "08:45", evento: "Fim da anestesia", usuario: "Dr. Carlos Silva", timestamp: "2025-01-04T08:45:00Z" },
        { tempo: "09:00", evento: "Saída de sala", usuario: "Enf. Ana Silva", timestamp: "2025-01-04T09:00:00Z" },
        {
          tempo: "09:15",
          evento: "Transferido para SRPA",
          usuario: "Enf. Ana Silva",
          timestamp: "2025-01-04T09:15:00Z",
        },
        {
          tempo: "10:30",
          evento: "Saída da SRPA para Quarto",
          usuario: "Enf. Ana Silva",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tempo: "15:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. Carlos Silva",
          timestamp: "2025-01-04T15:00:00Z",
        },
      ],
      durationMinutes: 45, // 07:45 a 08:30
    },
    {
      id: "1",
      nome: "Fabiana Lopes Martins",
      idade: 54,
      cpf: "234.567.890-11",
      rg: "23.456.789-0",
      endereco: "Av. Paulista, 456 - Bela Vista - São Paulo/SP",
      telefone: "(11) 98888-7777",
      email: "fabiana.martins@email.com",
      convenio: "BRADESCO",
      numeroCartao: "234567890123456",
      procedimento: "Colecistectomia Videolaparosc.",
      cirurgiao: "Dra. Ricardo Salles",
      anestesista: "Dr. Paulo Mendes",
      instrumentadora: "Enf. Carla Lima",
      sala: 1,
      status: "CHAMADO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Paciente diabética, glicemia controlada",
      contatoEmergencia: "Roberto Martins (Marido)",
      telefoneEmergencia: "(11) 97777-6666",
      horarios: [],
      historico: [
        {
          data: "10/08/2022",
          procedimento: "Histerectomia",
          cirurgiao: "Dra. Ana Paula",
          hospital: "Hospital Central",
          observacoes: "Recuperação excelente",
        },
      ],
      contatosFamiliares: [
        { nome: "Roberto Martins", parentesco: "Marido", telefone: "(11) 97777-6666", receberNotificacoes: true },
        { nome: "Julia Martins", parentesco: "Filha", telefone: "(11) 96666-5555", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "09:30",
          evento: "Paciente chamado para preparação",
          usuario: "Recepção",
          timestamp: "2025-01-04T09:30:00Z",
        },
        {
          tempo: "09:45",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Carla Lima",
          timestamp: "2025-01-04T09:45:00Z",
        },
      ],
      durationMinutes: 0, // Ainda não iniciou
    },
    {
      id: "2",
      nome: "Jonas Pedroso Carvalho",
      idade: 72,
      cpf: "345.678.901-22",
      rg: "34.567.890-1",
      endereco: "Rua Augusta, 789 - Consolação - São Paulo/SP",
      telefone: "(11) 97777-6666",
      email: "jonas.carvalho@email.com",
      convenio: "GOLDEN",
      numeroCartao: "345678901234567",
      procedimento: "Histerectomia Vaginal",
      cirurgiao: "Dr. Fábio Moura",
      anestesista: "Dr. Ricardo Alves",
      instrumentadora: "Enf. Sandra Costa",
      sala: 1,
      status: "RECEPÇÃO",
      lateralidade: "N/A",
      alergias: "Alergia a contraste iodado",
      observacoes: "Paciente com histórico de IAM, em uso de AAS",
      contatoEmergencia: "Helena Carvalho (Filha)",
      telefoneEmergencia: "(11) 96666-5555",
      horarios: [],
      historico: [
        {
          data: "05/12/2021",
          procedimento: "Angioplastia",
          cirurgiao: "Dr. Carlos Cardoso",
          hospital: "Hospital do Coração",
          observacoes: "Procedimento bem-sucedido",
        },
      ],
      contatosFamiliares: [
        { nome: "Helena Carvalho", parentesco: "Filha", telefone: "(11) 96666-5555", receberNotificacoes: true },
        { nome: "Marcos Carvalho", parentesco: "Filho", telefone: "(11) 95555-4444", receberNotificacoes: false },
      ],
      timeline: [
        {
          tempo: "12:30",
          evento: "Paciente chegou ao hospital",
          usuario: "Recepção",
          timestamp: "2025-01-04T12:30:00Z",
        },
        { tempo: "12:45", evento: "Documentação em andamento", usuario: "Recepção", timestamp: "2025-01-04T12:45:00Z" },
      ],
      durationMinutes: 0,
    },
    {
      id: "3",
      nome: "Raquel Lima Andrade",
      idade: 47,
      cpf: "456.789.012-33",
      rg: "45.678.901-2",
      endereco: "Rua Oscar Freire, 321 - Jardins - São Paulo/SP",
      telefone: "(11) 96666-5555",
      email: "raquel.andrade@email.com",
      convenio: "PARTICULAR",
      numeroCartao: "N/A",
      procedimento: "Varizes Membros Inferiores",
      cirurgiao: "Dra. Letícia Noronha",
      anestesista: "Dr. Fernando Costa",
      instrumentadora: "Enf. Patricia Souza",
      sala: 1,
      status: "ALTA", // Changed to ALTA
      lateralidade: "BILATERAL",
      alergias: "Látex",
      observacoes: "Paciente com varizes grau III bilateral",
      contatoEmergencia: "Carlos Andrade (Marido)",
      telefoneEmergencia: "(11) 95555-4444",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "16:00",
          usuario: "Enf. Patricia Souza",
          timestamp: "2025-01-04T16:00:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "16:15",
          usuario: "Dr. Fernando Costa",
          timestamp: "2025-01-04T16:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "16:30",
          usuario: "Dra. Letícia Noronha",
          timestamp: "2025-01-04T16:30:00Z",
        },
        {
          tipo: "FIM DA CIRURGIA",
          horario: "18:00",
          usuario: "Dra. Letícia Noronha",
          timestamp: "2025-01-04T18:00:00Z",
        },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "18:15",
          usuario: "Dr. Fernando Costa",
          timestamp: "2025-01-04T18:15:00Z",
        },
        { tipo: "SAÍDA DE SALA", horario: "18:30", usuario: "Enf. Patricia Souza", timestamp: "2025-01-04T18:30:00Z" },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "Carlos Andrade", parentesco: "Marido", telefone: "(11) 95555-4444", receberNotificacoes: true },
        { nome: "Amanda Andrade", parentesco: "Filha", telefone: "(11) 94444-3333", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "15:30",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T15:30:00Z",
        },
        {
          tempo: "15:45",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Patricia Souza",
          timestamp: "2025-01-04T15:45:00Z",
        },
        {
          tempo: "16:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Patricia Souza",
          timestamp: "2025-01-04T16:00:00Z",
        },
        {
          tempo: "16:15",
          evento: "Início da anestesia",
          usuario: "Dr. Fernando Costa",
          timestamp: "2025-01-04T16:15:00Z",
        },
        {
          tempo: "16:30",
          evento: "Início da cirurgia",
          usuario: "Dra. Letícia Noronha",
          timestamp: "2025-01-04T16:30:00Z",
        },
        {
          tempo: "18:00",
          evento: "Fim da cirurgia",
          usuario: "Dra. Letícia Noronha",
          timestamp: "2025-01-04T18:00:00Z",
        },
        {
          tempo: "18:15",
          evento: "Fim da anestesia",
          usuario: "Dr. Fernando Costa",
          timestamp: "2025-01-04T18:15:00Z",
        },
        { tempo: "18:30", evento: "Saída de sala", usuario: "Enf. Patricia Souza", timestamp: "2025-01-04T18:30:00Z" },
        {
          tempo: "19:00",
          evento: "Paciente liberado para casa",
          usuario: "Dr. Fernando Costa",
          timestamp: "2025-01-04T19:00:00Z",
        },
      ],
      durationMinutes: 90, // 16:30 a 18:00
    },
    {
      id: "4",
      nome: "Luís Carlos Damasceno",
      idade: 68,
      cpf: "567.890.123-44",
      rg: "56.789.012-3",
      endereco: "Rua Haddock Lobo, 654 - Cerqueira César - São Paulo/SP",
      telefone: "(11) 95555-4444",
      email: "luis.damasceno@email.com",
      convenio: "UNIMED",
      numeroCartao: "567890123456789",
      procedimento: "Prostatectomia Radical Robótica",
      cirurgiao: "Dr. Daniel Tavares",
      anestesista: "Dr. Marcos Ribeiro",
      instrumentadora: "Enf. Juliana Alves",
      sala: 2,
      status: "EM ANDAMENTO",
      lateralidade: "N/A",
      alergias: "Morfina",
      observacoes: "PSA elevado, biópsia positiva para adenocarcinoma",
      contatoEmergencia: "Silvia Damasceno (Esposa)",
      telefoneEmergencia: "(11) 94444-3333",
      horarios: [
        { tipo: "ENTRADA EM SALA", horario: "07:00", usuario: "Enf. Juliana Alves", timestamp: "2025-01-04T07:00:00Z" },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "07:15",
          usuario: "Dr. Marcos Ribeiro",
          timestamp: "2025-01-04T07:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "07:30",
          usuario: "Dr. Daniel Tavares",
          timestamp: "2025-01-04T07:30:00Z",
        },
      ],
      historico: [
        {
          data: "20/06/2024",
          procedimento: "Biópsia de Próstata",
          cirurgiao: "Dr. Daniel Tavares",
          hospital: "Hospital São Paulo",
          observacoes: "Resultado positivo para adenocarcinoma",
        },
      ],
      contatosFamiliares: [
        { nome: "Silvia Damasceno", parentesco: "Esposa", telefone: "(11) 94444-3333", receberNotificacoes: true },
        { nome: "Ricardo Damasceno", parentesco: "Filho", telefone: "(11) 93333-2222", receberNotificacoes: true },
        { nome: "Fernanda Damasceno", parentesco: "Filha", telefone: "(11) 92222-1111", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "06:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T06:00:00Z",
        },
        {
          tempo: "06:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Juliana Alves",
          timestamp: "2025-01-04T06:30:00Z",
        },
        {
          tempo: "07:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Juliana Alves",
          timestamp: "2025-01-04T07:00:00Z",
        },
        {
          tempo: "07:15",
          evento: "Início da anestesia",
          usuario: "Dr. Marcos Ribeiro",
          timestamp: "2025-01-04T07:15:00Z",
        },
        {
          tempo: "07:30",
          evento: "Início da cirurgia",
          usuario: "Dr. Daniel Tavares",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tempo: "08:00",
          evento: "Cirurgia em andamento - Fase 1 concluída",
          usuario: "Dr. Daniel Tavares",
          timestamp: "2025-01-04T08:00:00Z",
        },
      ],
      durationMinutes: 0, // Em andamento
    },
    {
      id: "5",
      nome: "Márcia Soares Ribeiro",
      idade: 59,
      cpf: "678.901.234-55",
      rg: "67.890.123-4",
      endereco: "Av. Brigadeiro Faria Lima, 987 - Itaim Bibi - São Paulo/SP",
      telefone: "(11) 94444-3333",
      email: "marcia.ribeiro@email.com",
      convenio: "SULAMÉRICA",
      numeroCartao: "678901234567890",
      procedimento: "Facoemulsificação",
      cirurgiao: "Dra. Carolina Paes",
      anestesista: "Dr. Luiz Henrique",
      instrumentadora: "Enf. Beatriz Santos",
      sala: 2,
      status: "ALTA", // Changed to ALTA
      lateralidade: "DIREITO",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Catarata senil, AV 20/200 OD",
      contatoEmergencia: "José Ribeiro (Marido)",
      telefoneEmergencia: "(11) 93333-2222",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "13:00",
          usuario: "Enf. Beatriz Santos",
          timestamp: "2025-01-04T13:00:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "13:15",
          usuario: "Dr. Luiz Henrique",
          timestamp: "2025-01-04T13:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "13:30",
          usuario: "Dra. Carolina Paes",
          timestamp: "2025-01-04T13:30:00Z",
        },
        { tipo: "FIM DA CIRURGIA", horario: "14:15", usuario: "Dra. Carolina Paes", timestamp: "2025-01-04T14:15:00Z" },
        { tipo: "FIM DA ANESTESIA", horario: "14:30", usuario: "Dr. Luiz Henrique", timestamp: "2025-01-04T14:30:00Z" },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "José Ribeiro", parentesco: "Marido", telefone: "(11) 93333-2222", receberNotificacoes: true },
        { nome: "Carla Ribeiro", parentesco: "Filha", telefone: "(11) 92222-1111", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "12:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T12:00:00Z",
        },
        {
          tempo: "12:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Beatriz Santos",
          timestamp: "2025-01-04T12:30:00Z",
        },
        {
          tempo: "13:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Beatriz Santos",
          timestamp: "2025-01-04T13:00:00Z",
        },
        {
          tempo: "13:15",
          evento: "Início da anestesia",
          usuario: "Dr. Luiz Henrique",
          timestamp: "2025-01-04T13:15:00Z",
        },
        {
          tempo: "13:30",
          evento: "Início da cirurgia",
          usuario: "Dra. Carolina Paes",
          timestamp: "2025-01-04T13:30:00Z",
        },
        { tempo: "14:15", evento: "Fim da cirurgia", usuario: "Dra. Carolina Paes", timestamp: "2025-01-04T14:15:00Z" },
        { tempo: "14:30", evento: "Fim da anestesia", usuario: "Dr. Luiz Henrique", timestamp: "2025-01-04T14:30:00Z" },
        {
          tempo: "14:45",
          evento: "Transferido para APO",
          usuario: "Enf. Beatriz Santos",
          timestamp: "2025-01-04T14:45:00Z",
        },
        {
          tempo: "15:30",
          evento: "Saída da APO para Quarto",
          usuario: "Enf. Beatriz Santos",
          timestamp: "2025-01-04T15:30:00Z",
        },
        {
          tempo: "18:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. Luiz Henrique",
          timestamp: "2025-01-04T18:00:00Z",
        },
      ],
      durationMinutes: 45, // 13:30 a 14:15
    },
    {
      id: "6",
      nome: "Maria Pinto Fagundes",
      idade: 41,
      cpf: "789.012.345-66",
      rg: "78.901.234-5",
      endereco: "Rua Consolação, 456 - Consolação - São Paulo/SP",
      telefone: "(11) 93333-2222",
      email: "maria.fagundes@email.com",
      convenio: "BRADESCO",
      numeroCartao: "789012345678901",
      procedimento: "Laqueadura Tubária",
      cirurgiao: "Dr. Gustavo Vidal",
      anestesista: "Dra. Fernanda Lima",
      instrumentadora: "Enf. Roberta Costa",
      sala: 2,
      status: "ALTA", // Changed to ALTA
      lateralidade: "N/A",
      alergias: "Ibuprofeno",
      observacoes: "G3P2A1, deseja contracepção definitiva",
      contatoEmergencia: "Carlos Fagundes (Marido)",
      telefoneEmergencia: "(11) 92222-1111",
      horarios: [
        { tipo: "ENTRADA EM SALA", horario: "14:00", usuario: "Enf. Roberta Costa", timestamp: "2025-01-04T14:00:00Z" },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "14:15",
          usuario: "Dra. Fernanda Lima",
          timestamp: "2025-01-04T14:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "14:30",
          usuario: "Dr. Gustavo Vidal",
          timestamp: "2025-01-04T14:30:00Z",
        },
        { tipo: "FIM DA CIRURGIA", horario: "15:30", usuario: "Dr. Gustavo Vidal", timestamp: "2025-01-04T15:30:00Z" },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "15:45",
          usuario: "Dra. Fernanda Lima",
          timestamp: "2025-01-04T15:45:00Z",
        },
        { tipo: "SAÍDA DE SALA", horario: "16:00", usuario: "Enf. Roberta Costa", timestamp: "2025-01-04T16:00:00Z" },
      ],
      historico: [
        {
          data: "12/05/2019",
          procedimento: "Cesariana",
          cirurgiao: "Dr. Gustavo Vidal",
          hospital: "Hospital São Paulo",
          observacoes: "Nascimento do terceiro filho",
        },
      ],
      contatosFamiliares: [
        { nome: "Carlos Fagundes", parentesco: "Marido", telefone: "(11) 92222-1111", receberNotificacoes: true },
        { nome: "Ana Fagundes", parentesco: "Mãe", telefone: "(11) 91111-0000", receberNotificacoes: false },
      ],
      timeline: [
        {
          tempo: "13:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T13:00:00Z",
        },
        {
          tempo: "13:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Roberta Costa",
          timestamp: "2025-01-04T13:30:00Z",
        },
        {
          tempo: "14:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Roberta Costa",
          timestamp: "2025-01-04T14:00:00Z",
        },
        {
          tempo: "14:15",
          evento: "Início da anestesia",
          usuario: "Dra. Fernanda Lima",
          timestamp: "2025-01-04T14:15:00Z",
        },
        {
          tempo: "14:30",
          evento: "Início da cirurgia",
          usuario: "Dr. Gustavo Vidal",
          timestamp: "2025-01-04T14:30:00Z",
        },
        { tempo: "15:30", evento: "Fim da cirurgia", usuario: "Dr. Gustavo Vidal", timestamp: "2025-01-04T15:30:00Z" },
        {
          tempo: "15:45",
          evento: "Fim da anestesia",
          usuario: "Dra. Fernanda Lima",
          timestamp: "2025-01-04T15:45:00Z",
        },
        { tempo: "16:00", evento: "Saída de sala", usuario: "Enf. Roberta Costa", timestamp: "2025-01-04T16:00:00Z" },
        {
          tempo: "16:30",
          evento: "Transferido para quarto",
          usuario: "Enf. Roberta Costa",
          timestamp: "2025-01-04T16:30:00Z",
        },
        {
          tempo: "20:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. Gustavo Vidal",
          timestamp: "2025-01-04T20:00:00Z",
        },
      ],
      durationMinutes: 60, // 14:30 a 15:30
    },
    {
      id: "7",
      nome: "Eliane de Castro Ferreira",
      idade: 66,
      cpf: "890.123.456-77",
      rg: "89.012.345-6",
      endereco: "Rua da Liberdade, 789 - Liberdade - São Paulo/SP",
      telefone: "(11) 92222-1111",
      email: "eliane.ferreira@email.com",
      convenio: "FUSEX",
      numeroCartao: "890123456789012",
      procedimento: "Histeroscopia Diagnóstica",
      cirurgiao: "Dr. Gustavo Vidal",
      anestesista: "Dr. Roberto Silva",
      instrumentadora: "Enf. Claudia Mendes",
      sala: 2,
      status: "ALTA", // Changed to ALTA
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Sangramento uterino anormal pós-menopausa",
      contatoEmergencia: "Paulo Ferreira (Filho)",
      telefoneEmergencia: "(11) 91111-0000",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "16:00",
          usuario: "Enf. Claudia Mendes",
          timestamp: "2025-01-04T16:00:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "16:15",
          usuario: "Dr. Roberto Silva",
          timestamp: "2025-01-04T16:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "16:30",
          usuario: "Dr. Gustavo Vidal",
          timestamp: "2025-01-04T16:30:00Z",
        },
        { tipo: "FIM DA CIRURGIA", horario: "17:00", usuario: "Dr. Gustavo Vidal", timestamp: "2025-01-04T17:00:00Z" },
        { tipo: "FIM DA ANESTESIA", horario: "17:15", usuario: "Dr. Roberto Silva", timestamp: "2025-01-04T17:15:00Z" },
        { tipo: "SAÍDA DE SALA", horario: "17:30", usuario: "Enf. Claudia Mendes", timestamp: "2025-01-04T17:30:00Z" },
      ],
      historico: [
        {
          data: "08/03/2020",
          procedimento: "Mamografia com Biópsia",
          cirurgiao: "Dr. Antonio Lopes",
          hospital: "Hospital Central",
          observacoes: "Resultado benigno",
        },
      ],
      contatosFamiliares: [
        { nome: "Paulo Ferreira", parentesco: "Filho", telefone: "(11) 91111-0000", receberNotificacoes: true },
        { nome: "Lucia Ferreira", parentesco: "Nora", telefone: "(11) 90000-9999", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "15:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T15:00:00Z",
        },
        {
          tempo: "15:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Claudia Mendes",
          timestamp: "2025-01-04T15:30:00Z",
        },
        {
          tempo: "16:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Claudia Mendes",
          timestamp: "2025-01-04T16:00:00Z",
        },
        {
          tempo: "16:15",
          evento: "Início da anestesia",
          usuario: "Dr. Roberto Silva",
          timestamp: "2025-01-04T16:15:00Z",
        },
        {
          tempo: "16:30",
          evento: "Início da cirurgia",
          usuario: "Dr. Gustavo Vidal",
          timestamp: "2025-01-04T16:30:00Z",
        },
        { tempo: "17:00", evento: "Fim da cirurgia", usuario: "Dr. Gustavo Vidal", timestamp: "2025-01-04T17:00:00Z" },
        { tempo: "17:15", evento: "Fim da anestesia", usuario: "Dr. Roberto Silva", timestamp: "2025-01-04T17:15:00Z" },
        { tempo: "17:30", evento: "Saída de sala", usuario: "Enf. Claudia Mendes", timestamp: "2025-01-04T17:30:00Z" },
        {
          tempo: "18:00",
          evento: "Paciente liberado para casa",
          usuario: "Dr. Roberto Silva",
          timestamp: "2025-01-04T18:00:00Z",
        },
      ],
      durationMinutes: 30, // 16:30 a 17:00
    },
    {
      id: "8",
      nome: "Jorge Almeida Rocha",
      idade: 50,
      cpf: "901.234.567-88",
      rg: "90.123.456-7",
      endereco: "Av. Ipiranga, 321 - República - São Paulo/SP",
      telefone: "(11) 91111-0000",
      email: "jorge.rocha@email.com",
      convenio: "UNIMED",
      numeroCartao: "901234567890123",
      procedimento: "Nefrolitotripsia Flexível",
      cirurgiao: "Dr. Leonardo S. Dias",
      anestesista: "Dr. Marcelo Santos",
      instrumentadora: "Enf. Vanessa Lima",
      sala: 3,
      status: "ALTA",
      lateralidade: "DIREITO",
      alergias: "Contraste iodado",
      observacoes: "Cálculo renal 15mm em pelve renal direita",
      contatoEmergencia: "Sandra Rocha (Esposa)",
      telefoneEmergencia: "(11) 90000-9999",
      horarios: [
        { tipo: "ENTRADA EM SALA", horario: "08:00", usuario: "Enf. Vanessa Lima", timestamp: "2025-01-04T08:00:00Z" },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "08:15",
          usuario: "Dr. Marcelo Santos",
          timestamp: "2025-01-04T08:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "08:30",
          usuario: "Dr. Leonardo S. Dias",
          timestamp: "2025-01-04T08:30:00Z",
        },
        {
          tipo: "FIM DA CIRURGIA",
          horario: "10:30",
          usuario: "Dr. Leonardo S. Dias",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "10:45",
          usuario: "Dr. Marcelo Santos",
          timestamp: "2025-01-04T10:45:00Z",
        },
        { tipo: "SAÍDA DE SALA", horario: "11:00", usuario: "Enf. Vanessa Lima", timestamp: "2025-01-04T11:00:00Z" },
      ],
      historico: [
        {
          data: "15/09/2022",
          procedimento: "Litotripsia Extracorpórea",
          cirurgiao: "Dr. Leonardo S. Dias",
          hospital: "Hospital São Paulo",
          observacoes: "Fragmentação parcial do cálculo",
        },
      ],
      contatosFamiliares: [
        { nome: "Sandra Rocha", parentesco: "Esposa", telefone: "(11) 90000-9999", receberNotificacoes: true },
        { nome: "Bruno Rocha", parentesco: "Filho", telefone: "(11) 89999-8888", receberNotificacoes: false },
      ],
      timeline: [
        {
          tempo: "07:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T07:00:00Z",
        },
        {
          tempo: "07:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Vanessa Lima",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tempo: "08:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Vanessa Lima",
          timestamp: "2025-01-04T08:00:00Z",
        },
        {
          tempo: "08:15",
          evento: "Início da anestesia",
          usuario: "Dr. Marcelo Santos",
          timestamp: "2025-01-04T08:15:00Z",
        },
        {
          tempo: "08:30",
          evento: "Início da cirurgia",
          usuario: "Dr. Leonardo S. Dias",
          timestamp: "2025-01-04T08:30:00Z",
        },
        {
          tempo: "10:30",
          evento: "Fim da cirurgia",
          usuario: "Dr. Leonardo S. Dias",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tempo: "10:45",
          evento: "Fim da anestesia",
          usuario: "Dr. Marcelo Santos",
          timestamp: "2025-01-04T10:45:00Z",
        },
        { tempo: "11:00", evento: "Saída de sala", usuario: "Enf. Vanessa Lima", timestamp: "2025-01-04T11:00:00Z" },
        {
          tempo: "11:15",
          evento: "Transferido para SRPA",
          usuario: "Enf. Vanessa Lima",
          timestamp: "2025-01-04T11:15:00Z",
        },
        {
          tempo: "12:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. Leonardo S. Dias",
          timestamp: "2025-01-04T12:00:00Z",
        },
      ],
      durationMinutes: 120, // 08:30 a 10:30
    },
    {
      id: "9",
      nome: "Simone Meirelles Dutra",
      idade: 37,
      cpf: "012.345.678-99",
      rg: "01.234.567-8",
      endereco: "Rua Bela Cintra, 654 - Consolação - São Paulo/SP",
      telefone: "(11) 90000-9999",
      email: "simone.dutra@email.com",
      convenio: "PARTICULAR",
      numeroCartao: "N/A",
      procedimento: "Colecistectomia Videolaparosc.",
      cirurgiao: "Dr. Eduardo Ramos",
      anestesista: "Dra. Patricia Alves",
      instrumentadora: "Enf. Monica Silva",
      sala: 3,
      status: "EM ANDAMENTO",
      lateralidade: "N/A",
      alergias: "Penicilina",
      observacoes: "Colelitíase sintomática, múltiplos cálculos",
      contatoEmergencia: "Ricardo Dutra (Marido)",
      telefoneEmergencia: "(11) 89999-8888",
      horarios: [
        { tipo: "ENTRADA EM SALA", horario: "09:00", usuario: "Enf. Monica Silva", timestamp: "2025-01-04T09:00:00Z" },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "09:15",
          usuario: "Dra. Patricia Alves",
          timestamp: "2025-01-04T09:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "09:30",
          usuario: "Dr. Eduardo Ramos",
          timestamp: "2025-01-04T09:30:00Z",
        },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "Ricardo Dutra", parentesco: "Marido", telefone: "(11) 89999-8888", receberNotificacoes: true },
        { nome: "Isabel Meirelles", parentesco: "Mãe", telefone: "(11) 88888-7777", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "08:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T08:00:00Z",
        },
        {
          tempo: "08:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Monica Silva",
          timestamp: "2025-01-04T08:30:00Z",
        },
        {
          tempo: "09:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Monica Silva",
          timestamp: "2025-01-04T09:00:00Z",
        },
        {
          tempo: "09:15",
          evento: "Início da anestesia",
          usuario: "Dra. Patricia Alves",
          timestamp: "2025-01-04T09:15:00Z",
        },
        {
          tempo: "09:30",
          evento: "Início da cirurgia",
          usuario: "Dr. Eduardo Ramos",
          timestamp: "2025-01-04T09:30:00Z",
        },
        {
          tempo: "10:00",
          evento: "Cirurgia em andamento - Pneumoperitônio realizado",
          usuario: "Dr. Eduardo Ramos",
          timestamp: "2025-01-04T10:00:00Z",
        },
      ],
      durationMinutes: 0,
    },
    {
      id: "10",
      nome: "Nelson Garcia Teixeira",
      idade: 41,
      cpf: "123.456.789-10",
      rg: "12.345.678-0",
      endereco: "Av. Rebouças, 987 - Pinheiros - São Paulo/SP",
      telefone: "(11) 89999-8888",
      email: "nelson.teixeira@email.com",
      convenio: "CASSI",
      numeroCartao: "123456789012340",
      procedimento: "By-pass gástrico",
      cirurgiao: "Dr. Eduardo Ramos",
      anestesista: "Dr. Felipe Costa",
      instrumentadora: "Enf. Adriana Santos",
      sala: 3,
      status: "CHAMADO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "IMC 42, diabetes tipo 2, hipertensão",
      contatoEmergencia: "Cristina Teixeira (Esposa)",
      telefoneEmergencia: "(11) 88888-7777",
      horarios: [],
      historico: [
        {
          data: "20/01/2023",
          procedimento: "Endoscopia Digestiva Alta",
          cirurgiao: "Dr. Carlos Mendes",
          hospital: "Hospital Central",
          observacoes: "Gastrite leve, H. pylori negativo",
        },
      ],
      contatosFamiliares: [
        { nome: "Cristina Teixeira", parentesco: "Esposa", telefone: "(11) 88888-7777", receberNotificacoes: true },
        { nome: "Gabriel Teixeira", parentesco: "Filho", telefone: "(11) 87777-6666", receberNotificacoes: false },
      ],
      timeline: [
        {
          tempo: "10:30",
          evento: "Paciente chamado para preparação",
          usuario: "Recepção",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tempo: "10:45",
          evento: "Avaliação pré-anestésica em andamento",
          usuario: "Dr. Felipe Costa",
          timestamp: "2025-01-04T10:45:00Z",
        },
      ],
      durationMinutes: 0,
    },
    {
      id: "11",
      nome: "Roberta Soares Silveira",
      idade: 34,
      cpf: "234.567.890-21",
      rg: "23.456.789-1",
      endereco: "Rua Pamplona, 456 - Jardim Paulista - São Paulo/SP",
      telefone: "(11) 88888-7777",
      email: "roberta.silveira@email.com",
      convenio: "BRADESCO",
      numeroCartao: "234567890123451",
      procedimento: "Artroscopia de Joelho",
      cirurgiao: "Dra. Fernanda C. Luz",
      anestesista: "Dr. Rodrigo Lima",
      instrumentadora: "Enf. Camila Costa",
      sala: 3,
      status: "CANCELADO", // Alterado para CANCELADO
      lateralidade: "ESQUERDO",
      alergias: "Dipirona",
      observacoes: "Lesão de menisco medial, atleta recreativa",
      cancellationReason: "Paciente com sintomas gripais", // Motivo do cancelamento
      contatoEmergencia: "Marcos Silveira (Marido)",
      telefoneEmergencia: "(11) 87777-6666",
      horarios: [],
      historico: [
        {
          data: "10/06/2023",
          procedimento: "Ressonância Magnética de Joelho",
          cirurgiao: "Dr. Radiologista",
          hospital: "Centro de Diagnóstico",
          observacoes: "Lesão complexa de menisco medial",
        },
      ],
      contatosFamiliares: [
        { nome: "Marcos Silveira", parentesco: "Marido", telefone: "(11) 87777-6666", receberNotificacoes: true },
        { nome: "Ana Soares", parentesco: "Mãe", telefone: "(11) 86666-5555", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "12:30",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T12:30:00Z",
        },
        {
          tempo: "12:45",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Recepção",
          timestamp: "2025-01-04T12:45:00Z",
        },
      ],
      durationMinutes: 0,
    },
    {
      id: "12",
      nome: "Otávio Marques Gonçalves",
      idade: 64,
      cpf: "345.678.901-32",
      rg: "34.567.890-2",
      endereco: "Rua Estados Unidos, 789 - Jardim América - São Paulo/SP",
      telefone: "(11) 87777-6666",
      email: "otavio.goncalves@email.com",
      convenio: "GOLDEN",
      numeroCartao: "345678901234562",
      procedimento: "Osteossíntese de Úmero",
      cirurgiao: "Dr. Carlos H. Bittencourt",
      anestesista: "Dr. Anderson Silva",
      instrumentadora: "Enf. Priscila Lima",
      sala: 4,
      status: "ALTA", // Changed to ALTA
      lateralidade: "DIREITO",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Fratura de úmero proximal pós-queda",
      contatoEmergencia: "Vera Gonçalves (Esposa)",
      telefoneEmergencia: "(11) 86666-5555",
      horarios: [
        { tipo: "ENTRADA EM SALA", horario: "07:15", usuario: "Enf. Priscila Lima", timestamp: "2025-01-04T07:15:00Z" },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "07:30",
          usuario: "Dr. Anderson Silva",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "07:45",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T07:45:00Z",
        },
        {
          tipo: "FIM DA CIRURGIA",
          horario: "09:45",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T09:45:00Z",
        },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "10:00",
          usuario: "Dr. Anderson Silva",
          timestamp: "2025-01-04T10:00:00Z",
        },
      ],
      historico: [
        {
          data: "05/11/2021",
          procedimento: "Artroscopia de Ombro",
          cirurgiao: "Dr. Carlos H. Bittencourt",
          hospital: "Hospital Ortopédico",
          observacoes: "Reparo de manguito rotador",
        },
      ],
      contatosFamiliares: [
        { nome: "Vera Gonçalves", parentesco: "Esposa", telefone: "(11) 86666-5555", receberNotificacoes: true },
        { nome: "Pedro Gonçalves", parentesco: "Filho", telefone: "(11) 85555-4444", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "06:30",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T06:30:00Z",
        },
        {
          tempo: "07:00",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Priscila Lima",
          timestamp: "2025-01-04T07:00:00Z",
        },
        {
          tempo: "07:15",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Priscila Lima",
          timestamp: "2025-01-04T07:15:00Z",
        },
        {
          tempo: "07:30",
          evento: "Início da anestesia",
          usuario: "Dr. Anderson Silva",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tempo: "07:45",
          evento: "Início da cirurgia",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T07:45:00Z",
        },
        {
          tempo: "09:45",
          evento: "Fim da cirurgia",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T09:45:00Z",
        },
        {
          tempo: "10:00",
          evento: "Fim da anestesia",
          usuario: "Dr. Anderson Silva",
          timestamp: "2025-01-04T10:00:00Z",
        },
        { tempo: "10:15", evento: "Saída de sala", usuario: "Enf. Priscila Lima", timestamp: "2025-01-04T10:15:00Z" },
        {
          tempo: "10:30",
          evento: "Transferido para SRPA",
          usuario: "Enf. Priscila Lima",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tempo: "11:30",
          evento: "Saída da SRPA para Quarto",
          usuario: "Enf. Priscila Lima",
          timestamp: "2025-01-04T11:30:00Z",
        },
        {
          tempo: "14:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T14:00:00Z",
        },
      ],
      durationMinutes: 120, // 07:45 a 09:45
    },
    {
      id: "13",
      nome: "Beatriz Antunes Ferreira",
      idade: 25,
      cpf: "456.789.012-43",
      rg: "45.678.901-3",
      endereco: "Av. Paulista, 1234 - Bela Vista - São Paulo/SP",
      telefone: "(11) 86666-5555",
      email: "beatriz.ferreira@email.com",
      convenio: "UNIMED",
      numeroCartao: "456789012345673",
      procedimento: "Artroplastia de quadril",
      cirurgiao: "Dr. Carlos H. Bittencourt",
      anestesista: "Dra. Juliana Mendes",
      instrumentadora: "Enf. Fernanda Silva",
      sala: 4,
      status: "EM ANDAMENTO",
      lateralidade: "DIREITO",
      alergias: "Látex, Iodo",
      observacoes: "Displasia congênita do quadril, jovem atleta",
      contatoEmergencia: "Maria Antunes (Mãe)",
      telefoneEmergencia: "(11) 85555-4444",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "09:30",
          usuario: "Enf. Fernanda Silva",
          timestamp: "2025-01-04T09:30:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "09:45",
          usuario: "Dra. Juliana Mendes",
          timestamp: "2025-01-04T09:45:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "10:00",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T10:00:00Z",
        },
      ],
      historico: [
        {
          data: "15/08/2024",
          procedimento: "Artroscopia de Quadril",
          cirurgiao: "Dr. Carlos H. Bittencourt",
          hospital: "Hospital Ortopédico",
          observacoes: "Avaliação diagnóstica da displasia",
        },
      ],
      contatosFamiliares: [
        { nome: "Maria Antunes", parentesco: "Mãe", telefone: "(11) 85555-4444", receberNotificacoes: true },
        { nome: "João Ferreira", parentesco: "Pai", telefone: "(11) 84444-3333", receberNotificacoes: true },
        { nome: "Lucas Ferreira", parentesco: "Namorado", telefone: "(11) 83333-2222", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "08:30",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T08:30:00Z",
        },
        {
          tempo: "09:00",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Fernanda Silva",
          timestamp: "2025-01-04T09:00:00Z",
        },
        {
          tempo: "09:30",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Fernanda Silva",
          timestamp: "2025-01-04T09:30:00Z",
        },
        {
          tempo: "09:45",
          evento: "Início da anestesia",
          usuario: "Dra. Juliana Mendes",
          timestamp: "2025-01-04T09:45:00Z",
        },
        {
          tempo: "10:00",
          evento: "Início da cirurgia",
          usuario: "Dr. Carlos H. Bittencourt",
          timestamp: "2025-01-04T10:00:00Z",
        },
      ],
      durationMinutes: 0,
    },
    {
      id: "14",
      nome: "Pedro Vitor Saldanha",
      idade: 39,
      cpf: "567.890.123-54",
      rg: "56.789.012-4",
      endereco: "Rua Augusta, 2468 - Consolação - São Paulo/SP",
      telefone: "(11) 85555-4444",
      email: "pedro.saldanha@email.com",
      convenio: "AMIL",
      numeroCartao: "567890123456784",
      procedimento: "Cirurgia de Hemorroida",
      cirurgiao: "Dr. Álvaro Gonçalves",
      anestesista: "Dr. Thiago Santos",
      instrumentadora: "Enf. Larissa Costa",
      sala: 4,
      status: "APO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Hemorroidas grau III, sintomas há 2 anos",
      contatoEmergencia: "Amanda Saldanha (Esposa)",
      telefoneEmergencia: "(11) 84444-3333",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "13:00",
          usuario: "Enf. Larissa Costa",
          timestamp: "2025-01-04T13:00:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "13:15",
          usuario: "Dr. Thiago Santos",
          timestamp: "2025-01-04T13:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "13:30",
          usuario: "Dr. Álvaro Gonçalves",
          timestamp: "2025-01-04T13:30:00Z",
        },
        {
          tipo: "FIM DA CIRURGIA",
          horario: "14:30",
          usuario: "Dr. Álvaro Gonçalves",
          timestamp: "2025-01-04T14:30:00Z",
        },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "14:45",
          usuario: "Dr. Thiago Santos",
          timestamp: "2025-01-04T14:45:00Z",
        },
        { tipo: "SAÍDA DE SALA", horario: "15:00", usuario: "Enf. Larissa Costa", timestamp: "2025-01-04T15:00:00Z" },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "Amanda Saldanha", parentesco: "Esposa", telefone: "(11) 84444-3333", receberNotificacoes: true },
        { nome: "Lucas Saldanha", parentesco: "Filho", telefone: "(11) 83333-2222", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "12:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T12:00:00Z",
        },
        {
          tempo: "12:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Larissa Costa",
          timestamp: "2025-01-04T12:30:00Z",
        },
        {
          tempo: "13:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Larissa Costa",
          timestamp: "2025-01-04T13:00:00Z",
        },
        {
          tempo: "13:15",
          evento: "Início da anestesia",
          usuario: "Dr. Thiago Santos",
          timestamp: "2025-01-04T13:15:00Z",
        },
        {
          tempo: "13:30",
          evento: "Início da cirurgia",
          usuario: "Dr. Álvaro Gonçalves",
          timestamp: "2025-01-04T13:30:00Z",
        },
        {
          tempo: "14:30",
          evento: "Fim da cirurgia",
          usuario: "Dr. Álvaro Gonçalves",
          timestamp: "2025-01-04T14:30:00Z",
        },
        {
          tempo: "14:45",
          evento: "Fim da anestesia",
          usuario: "Dr. Thiago Santos",
          timestamp: "2025-01-04T14:45:00Z",
        },
        { tempo: "15:00", evento: "Saída de sala", usuario: "Enf. Larissa Costa", timestamp: "2025-01-04T15:00:00Z" },
        {
          tempo: "15:15",
          evento: "Transferido para APO",
          usuario: "Enf. Larissa Costa",
          timestamp: "2025-01-04T15:15:00Z",
        },
        {
          tempo: "16:00",
          evento: "Saída da APO para Quarto",
          usuario: "Enf. Larissa Costa",
          timestamp: "2025-01-04T16:00:00Z",
        },
        {
          tempo: "18:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. Álvaro Gonçalves",
          timestamp: "2025-01-04T18:00:00Z",
        },
      ],
      durationMinutes: 60, // 13:30 a 14:30
    },
    {
      id: "15",
      nome: "Elza Maria Coimbra",
      idade: 73,
      cpf: "678.901.234-65",
      rg: "67.890.123-5",
      endereco: "Rua Bela Cintra, 1357 - Consolação - São Paulo/SP",
      telefone: "(11) 84444-3333",
      email: "elza.coimbra@email.com",
      convenio: "UNIMED",
      numeroCartao: "678901234567895",
      procedimento: "Reconstrução de Parede Abdominal",
      cirurgiao: "Dra. Patrícia Fontes",
      anestesista: "Dr. Gustavo Lima",
      instrumentadora: "Enf. Renata Santos",
      sala: 4,
      status: "CTI",
      lateralidade: "N/A",
      alergias: "Penicilina, Sulfa",
      observacoes: "Hérnia incisional complexa, múltiplas comorbidades",
      contatoEmergencia: "Carlos Coimbra (Filho)",
      telefoneEmergencia: "(11) 83333-2222",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "08:00",
          usuario: "Enf. Renata Santos",
          timestamp: "2025-01-04T08:00:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "08:15",
          usuario: "Dr. Gustavo Lima",
          timestamp: "2025-01-04T08:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "08:30",
          usuario: "Dra. Patrícia Fontes",
          timestamp: "2025-01-04T08:30:00Z",
        },
        {
          tipo: "FIM DA CIRURGIA",
          horario: "11:30",
          usuario: "Dra. Patrícia Fontes",
          timestamp: "2025-01-04T11:30:00Z",
        },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "11:45",
          usuario: "Dr. Gustavo Lima",
          timestamp: "2025-01-04T11:45:00Z",
        },
        { tipo: "SAÍDA DE SALA", horario: "12:00", usuario: "Enf. Renata Santos", timestamp: "2025-01-04T12:00:00Z" },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "Carlos Coimbra", parentesco: "Filho", telefone: "(11) 83333-2222", receberNotificacoes: true },
        { nome: "Fernanda Coimbra", parentesco: "Neta", telefone: "(11) 82222-1111", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "07:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T07:00:00Z",
        },
        {
          tempo: "07:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Renata Santos",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tempo: "08:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Renata Santos",
          timestamp: "2025-01-04T08:00:00Z",
        },
        {
          tempo: "08:15",
          evento: "Início da anestesia",
          usuario: "Dr. Gustavo Lima",
          timestamp: "2025-01-04T08:15:00Z",
        },
        {
          tempo: "08:30",
          evento: "Início da cirurgia",
          usuario: "Dra. Patrícia Fontes",
          timestamp: "2025-01-04T08:30:00Z",
        },
        {
          tempo: "11:30",
          evento: "Fim da cirurgia",
          usuario: "Dra. Patrícia Fontes",
          timestamp: "2025-01-04T11:30:00Z",
        },
        {
          tempo: "11:45",
          evento: "Fim da anestesia",
          usuario: "Dr. Gustavo Lima",
          timestamp: "2025-01-04T11:45:00Z",
        },
        { tempo: "12:00", evento: "Saída de sala", usuario: "Enf. Renata Santos", timestamp: "2025-01-04T12:00:00Z" },
        {
          tempo: "12:15",
          evento: "Transferido para CTI",
          usuario: "Enf. Renata Santos",
          timestamp: "2025-01-04T12:15:00Z",
        },
        {
          tempo: "18:00",
          evento: "Paciente recebeu alta",
          usuario: "Dra. Patrícia Fontes",
          timestamp: "2025-01-04T18:00:00Z",
        },
      ],
      durationMinutes: 180, // 08:30 a 11:30
    },
    {
      id: "16",
      nome: "Bruno César Machado",
      idade: 22,
      cpf: "789.012.345-76",
      rg: "78.901.234-6",
      endereco: "Av. Brigadeiro Luis Antonio, 987 - Bela Vista - São Paulo/SP",
      telefone: "(11) 83333-2222",
      email: "bruno.machado@email.com",
      convenio: "SULAMÉRICA",
      numeroCartao: "789012345678906",
      procedimento: "Orquiectomia",
      cirurgiao: "Dr. Henrique de Sá",
      anestesista: "Dr. Rafael Costa",
      instrumentadora: "Enf. Tatiana Lima",
      sala: 5,
      status: "EM ANDAMENTO",
      lateralidade: "ESQUERDO",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Tumor testicular, marcadores elevados",
      contatoEmergencia: "Lucia Machado (Mãe)",
      telefoneEmergencia: "(11) 82222-1111",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "07:45",
          usuario: "Enf. Tatiana Lima",
          timestamp: "2025-01-04T07:45:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "08:00",
          usuario: "Dr. Rafael Costa",
          timestamp: "2025-01-04T08:00:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "08:15",
          usuario: "Dr. Henrique de Sá",
          timestamp: "2025-01-04T08:15:00Z",
        },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "Lucia Machado", parentesco: "Mãe", telefone: "(11) 82222-1111", receberNotificacoes: true },
        { nome: "Gustavo Machado", parentesco: "Irmão", telefone: "(11) 81111-0000", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "07:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T07:00:00Z",
        },
        {
          tempo: "07:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Tatiana Lima",
          timestamp: "2025-01-04T07:30:00Z",
        },
        {
          tempo: "07:45",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Tatiana Lima",
          timestamp: "2025-01-04T07:45:00Z",
        },
        {
          tempo: "08:00",
          evento: "Início da anestesia",
          usuario: "Dr. Rafael Costa",
          timestamp: "2025-01-04T08:00:00Z",
        },
        {
          tempo: "08:15",
          evento: "Início da cirurgia",
          usuario: "Dr. Henrique de Sá",
          timestamp: "2025-01-04T08:15:00Z",
        },
      ],
      durationMinutes: 0,
    },
    {
      id: "17",
      nome: "Luciana Esteves Paiva",
      idade: 36,
      cpf: "890.123.456-87",
      rg: "89.012.345-7",
      endereco: "Rua Oscar Freire, 654 - Jardins - São Paulo/SP",
      telefone: "(11) 82222-1111",
      email: "luciana.paiva@email.com",
      convenio: "BRADESCO",
      numeroCartao: "890123456789017",
      procedimento: "Histerectomia Videolaparoscópica",
      cirurgiao: "Dra. Lúcia Andrade",
      anestesista: "Dr. Marcelo Ribeiro",
      instrumentadora: "Enf. Silvia Santos",
      sala: 5,
      status: "CHAMADO",
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Miomatose uterina, sangramento abundante",
      contatoEmergencia: "Fernando Paiva (Marido)",
      telefoneEmergencia: "(11) 81111-0000",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [
        {
          tempo: "09:00",
          evento: "Paciente chamado para preparação",
          usuario: "Recepção",
          timestamp: "2025-01-04T09:00:00Z",
        },
        {
          tempo: "09:15",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Silvia Santos",
          timestamp: "2025-01-04T09:15:00Z",
        },
      ],
      durationMinutes: 0,
    },
    {
      id: "18",
      nome: "Edson Alves Guimarães",
      idade: 53,
      cpf: "901.234.567-98",
      rg: "90.123.456-8",
      endereco: "Av. Faria Lima, 1234 - Itaim Bibi - São Paulo/SP",
      telefone: "(11) 81111-0000",
      email: "edson.guimaraes@email.com",
      convenio: "UNIMED",
      numeroCartao: "901234567890128",
      procedimento: "Vasectomia",
      cirurgiao: "Dr. André Peixoto",
      anestesista: "Dr. Paulo Santos",
      instrumentadora: "Enf. Cristina Lima",
      sala: 5,
      status: "ALTA", // Changed to ALTA
      lateralidade: "N/A",
      alergias: "Nenhuma alergia conhecida",
      observacoes: "Prole constituída, deseja contracepção definitiva",
      contatoEmergencia: "Patricia Guimarães (Esposa)",
      telefoneEmergencia: "(11) 80000-9999",
      horarios: [
        {
          tipo: "ENTRADA EM SALA",
          horario: "10:00",
          usuario: "Enf. Cristina Lima",
          timestamp: "2025-01-04T10:00:00Z",
        },
        {
          tipo: "INÍCIO DA ANESTESIA",
          horario: "10:15",
          usuario: "Dr. Paulo Santos",
          timestamp: "2025-01-04T10:15:00Z",
        },
        {
          tipo: "INÍCIO DA CIRURGIA",
          horario: "10:30",
          usuario: "Dr. André Peixoto",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tipo: "FIM DA CIRURGIA",
          horario: "11:00",
          usuario: "Dr. André Peixoto",
          timestamp: "2025-01-04T11:00:00Z",
        },
        {
          tipo: "FIM DA ANESTESIA",
          horario: "11:15",
          usuario: "Dr. Paulo Santos",
          timestamp: "2025-01-04T11:15:00Z",
        },
        { tipo: "SAÍDA DE SALA", horario: "11:30", usuario: "Enf. Cristina Lima", timestamp: "2025-01-04T11:30:00Z" },
      ],
      historico: [],
      contatosFamiliares: [
        { nome: "Patricia Guimarães", parentesco: "Esposa", telefone: "(11) 80000-9999", receberNotificacoes: true },
        { nome: "Felipe Guimarães", parentesco: "Filho", telefone: "(11) 79999-8888", receberNotificacoes: true },
      ],
      timeline: [
        {
          tempo: "09:00",
          evento: "Paciente admitido na unidade",
          usuario: "Recepção",
          timestamp: "2025-01-04T09:00:00Z",
        },
        {
          tempo: "09:30",
          evento: "Preparação pré-operatória iniciada",
          usuario: "Enf. Cristina Lima",
          timestamp: "2025-01-04T09:30:00Z",
        },
        {
          tempo: "10:00",
          evento: "Entrada em sala cirúrgica",
          usuario: "Enf. Cristina Lima",
          timestamp: "2025-01-04T10:00:00Z",
        },
        {
          tempo: "10:15",
          evento: "Início da anestesia",
          usuario: "Dr. Paulo Santos",
          timestamp: "2025-01-04T10:15:00Z",
        },
        {
          tempo: "10:30",
          evento: "Início da cirurgia",
          usuario: "Dr. André Peixoto",
          timestamp: "2025-01-04T10:30:00Z",
        },
        {
          tempo: "11:00",
          evento: "Fim da cirurgia",
          usuario: "Dr. André Peixoto",
          timestamp: "2025-01-04T11:00:00Z",
        },
        {
          tempo: "11:15",
          evento: "Fim da anestesia",
          usuario: "Dr. Paulo Santos",
          timestamp: "2025-01-04T11:15:00Z",
        },
        { tempo: "11:30", evento: "Saída de sala", usuario: "Enf. Cristina Lima", timestamp: "2025-01-04T11:30:00Z" },
        {
          tempo: "11:45",
          evento: "Transferido para APO",
          usuario: "Enf. Cristina Lima",
          timestamp: "2025-01-04T11:45:00Z",
        },
        {
          tempo: "12:30",
          evento: "Saída da APO para Casa",
          usuario: "Enf. Cristina Lima",
          timestamp: "2025-01-04T12:30:00Z",
        },
        {
          tempo: "13:00",
          evento: "Paciente recebeu alta",
          usuario: "Dr. André Peixoto",
          timestamp: "2025-01-04T13:00:00Z",
        },
      ],
      durationMinutes: 30, // 10:30 a 11:00
    },
    {
      id: "19",
      nome: "Carlos Maia Marcondes",
      idade: 61,
      cpf: "012.345.678-09",
      rg: "01.234.567-9",
      endereco: "Rua Haddock Lobo, 2468 - Jardim Paulista - São Paulo/SP",
      telefone: "(11) 80000-9999",
      email: "carlos.marcondes@email.com",
      convenio: "AMIL",
      numeroCartao: "012345678901239",
      procedimento: "Vasectomia",
      cirurgiao: "Dr. André Peixoto",
      anestesista: "Dr. Sergio Lima",
      instrumentadora: "Enf. Daniela Costa",
      sala: 5,
      status: "CANCELADO", // Changed to CANCELADO
      lateralidade: "N/A",
      alergias: "Dipirona",
      observacoes: "Prole constituída, 3 filhos adultos",
      cancellationReason: "Problemas de agenda do cirurgião", // Motivo do cancelamento
      contatoEmergencia: "Marisa Marcondes (Esposa)",
      telefoneEmergencia: "(11) 79999-8888",
      horarios: [],
      historico: [],
      contatosFamiliares: [],
      timeline: [
        {
          tempo: "09:00",
          evento: "Paciente chegou ao hospital",
          usuario: "Recepção",
          timestamp: "2025-01-04T09:00:00Z",
        },
        {
          tempo: "09:30",
          evento: "Cancelamento da cirurgia",
          usuario: "Administração",
          timestamp: "2025-01-04T09:30:00Z",
        },
      ],
      durationMinutes: 0,
    },
  ]
}
